// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gbt3260.proto
package com.nevt.gbt32960.message;

/**
 * Protobuf type {@code ConfigQueryRequest}
 */
public final class ConfigQueryRequest extends
        com.google.protobuf.GeneratedMessageV3 implements
        ConfigQueryRequestOrBuilder {
    private ConfigQueryRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    private ConfigQueryRequest() {
        queryTime_ = 0L;
        parameterIds_ = java.util.Collections.emptyList();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
        return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }

    private ConfigQueryRequest(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        int mutable_bitField0_ = 0;
        try {
            boolean done = false;
            while (!done) {
                int tag = input.readTag();
                switch (tag) {
                    case 0:
                        done = true;
                        break;
                    default: {
                        if (!input.skipField(tag)) {
                            done = true;
                        }
                        break;
                    }
                    case 8: {

                        queryTime_ = input.readInt64();
                        break;
                    }
                    case 16: {
                        if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                            parameterIds_ = new java.util.ArrayList<Integer>();
                            mutable_bitField0_ |= 0x00000002;
                        }
                        parameterIds_.add(input.readInt32());
                        break;
                    }
                    case 18: {
                        int length = input.readRawVarint32();
                        int limit = input.pushLimit(length);
                        if (!((mutable_bitField0_ & 0x00000002) == 0x00000002) && input.getBytesUntilLimit() > 0) {
                            parameterIds_ = new java.util.ArrayList<Integer>();
                            mutable_bitField0_ |= 0x00000002;
                        }
                        while (input.getBytesUntilLimit() > 0) {
                            parameterIds_.add(input.readInt32());
                        }
                        input.popLimit(limit);
                        break;
                    }
                }
            }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(
                    e).setUnfinishedMessage(this);
        } finally {
            if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                parameterIds_ = java.util.Collections.unmodifiableList(parameterIds_);
            }
            makeExtensionsImmutable();
        }
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
        return Gbt3260.internal_static_com_ime_iov_gbt32960_ConfigQueryRequest_descriptor;
    }

    protected FieldAccessorTable
    internalGetFieldAccessorTable() {
        return Gbt3260.internal_static_com_ime_iov_gbt32960_ConfigQueryRequest_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        ConfigQueryRequest.class, Builder.class);
    }

    private int bitField0_;
    public static final int QUERY_TIME_FIELD_NUMBER = 1;
    private long queryTime_;

    /**
     * <code>optional int64 query_time = 1;</code>
     */
    public long getQueryTime() {
        return queryTime_;
    }

    public static final int PARAMETER_IDS_FIELD_NUMBER = 2;
    private java.util.List<Integer> parameterIds_;

    /**
     * <code>repeated int32 parameter_ids = 2;</code>
     */
    public java.util.List<Integer>
    getParameterIdsList() {
        return parameterIds_;
    }

    /**
     * <code>repeated int32 parameter_ids = 2;</code>
     */
    public int getParameterIdsCount() {
        return parameterIds_.size();
    }

    /**
     * <code>repeated int32 parameter_ids = 2;</code>
     */
    public int getParameterIds(int index) {
        return parameterIds_.get(index);
    }

    private int parameterIdsMemoizedSerializedSize = -1;

    private byte memoizedIsInitialized = -1;

    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
        getSerializedSize();
        if (queryTime_ != 0L) {
            output.writeInt64(1, queryTime_);
        }
        if (getParameterIdsList().size() > 0) {
            output.writeUInt32NoTag(18);
            output.writeUInt32NoTag(parameterIdsMemoizedSerializedSize);
        }
        for (int i = 0; i < parameterIds_.size(); i++) {
            output.writeInt32NoTag(parameterIds_.get(i));
        }
    }

    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (queryTime_ != 0L) {
            size += com.google.protobuf.CodedOutputStream
                    .computeInt64Size(1, queryTime_);
        }
        {
            int dataSize = 0;
            for (int i = 0; i < parameterIds_.size(); i++) {
                dataSize += com.google.protobuf.CodedOutputStream
                        .computeInt32SizeNoTag(parameterIds_.get(i));
            }
            size += dataSize;
            if (!getParameterIdsList().isEmpty()) {
                size += 1;
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32SizeNoTag(dataSize);
            }
            parameterIdsMemoizedSerializedSize = dataSize;
        }
        memoizedSize = size;
        return size;
    }

    private static final long serialVersionUID = 0L;

    @Override
    public boolean equals(final Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof ConfigQueryRequest)) {
            return super.equals(obj);
        }
        ConfigQueryRequest other = (ConfigQueryRequest) obj;

        boolean result = true;
        result = result && (getQueryTime()
                == other.getQueryTime());
        result = result && getParameterIdsList()
                .equals(other.getParameterIdsList());
        return result;
    }

    @Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptorForType().hashCode();
        hash = (37 * hash) + QUERY_TIME_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                getQueryTime());
        if (getParameterIdsCount() > 0) {
            hash = (37 * hash) + PARAMETER_IDS_FIELD_NUMBER;
            hash = (53 * hash) + getParameterIdsList().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public static ConfigQueryRequest parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static ConfigQueryRequest parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static ConfigQueryRequest parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static ConfigQueryRequest parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static ConfigQueryRequest parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static ConfigQueryRequest parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static ConfigQueryRequest parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input);
    }

    public static ConfigQueryRequest parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static ConfigQueryRequest parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static ConfigQueryRequest parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() {
        return newBuilder();
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(ConfigQueryRequest prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
                ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
            BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    /**
     * Protobuf type {@code ConfigQueryRequest}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:ConfigQueryRequest)
            ConfigQueryRequestOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return Gbt3260.internal_static_com_ime_iov_gbt32960_ConfigQueryRequest_descriptor;
        }

        protected FieldAccessorTable
        internalGetFieldAccessorTable() {
            return Gbt3260.internal_static_com_ime_iov_gbt32960_ConfigQueryRequest_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            ConfigQueryRequest.class, Builder.class);
        }

        // Construct using ConfigQueryRequest.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private Builder(
                BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
        }

        private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessageV3
                    .alwaysUseFieldBuilders) {
            }
        }

        public Builder clear() {
            super.clear();
            queryTime_ = 0L;

            parameterIds_ = java.util.Collections.emptyList();
            bitField0_ = (bitField0_ & ~0x00000002);
            return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
            return Gbt3260.internal_static_com_ime_iov_gbt32960_ConfigQueryRequest_descriptor;
        }

        public ConfigQueryRequest getDefaultInstanceForType() {
            return ConfigQueryRequest.getDefaultInstance();
        }

        public ConfigQueryRequest build() {
            ConfigQueryRequest result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        public ConfigQueryRequest buildPartial() {
            ConfigQueryRequest result = new ConfigQueryRequest(this);
            int from_bitField0_ = bitField0_;
            int to_bitField0_ = 0;
            result.queryTime_ = queryTime_;
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                parameterIds_ = java.util.Collections.unmodifiableList(parameterIds_);
                bitField0_ = (bitField0_ & ~0x00000002);
            }
            result.parameterIds_ = parameterIds_;
            result.bitField0_ = to_bitField0_;
            onBuilt();
            return result;
        }

        public Builder clone() {
            return (Builder) super.clone();
        }

        public Builder setField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                Object value) {
            return (Builder) super.setField(field, value);
        }

        public Builder clearField(
                com.google.protobuf.Descriptors.FieldDescriptor field) {
            return (Builder) super.clearField(field);
        }

        public Builder clearOneof(
                com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return (Builder) super.clearOneof(oneof);
        }

        public Builder setRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                int index, Object value) {
            return (Builder) super.setRepeatedField(field, index, value);
        }

        public Builder addRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                Object value) {
            return (Builder) super.addRepeatedField(field, value);
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof ConfigQueryRequest) {
                return mergeFrom((ConfigQueryRequest) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(ConfigQueryRequest other) {
            if (other == ConfigQueryRequest.getDefaultInstance()) return this;
            if (other.getQueryTime() != 0L) {
                setQueryTime(other.getQueryTime());
            }
            if (!other.parameterIds_.isEmpty()) {
                if (parameterIds_.isEmpty()) {
                    parameterIds_ = other.parameterIds_;
                    bitField0_ = (bitField0_ & ~0x00000002);
                } else {
                    ensureParameterIdsIsMutable();
                    parameterIds_.addAll(other.parameterIds_);
                }
                onChanged();
            }
            onChanged();
            return this;
        }

        public final boolean isInitialized() {
            return true;
        }

        public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            ConfigQueryRequest parsedMessage = null;
            try {
                parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                parsedMessage = (ConfigQueryRequest) e.getUnfinishedMessage();
                throw e.unwrapIOException();
            } finally {
                if (parsedMessage != null) {
                    mergeFrom(parsedMessage);
                }
            }
            return this;
        }

        private int bitField0_;

        private long queryTime_;

        /**
         * <code>optional int64 query_time = 1;</code>
         */
        public long getQueryTime() {
            return queryTime_;
        }

        /**
         * <code>optional int64 query_time = 1;</code>
         */
        public Builder setQueryTime(long value) {

            queryTime_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>optional int64 query_time = 1;</code>
         */
        public Builder clearQueryTime() {

            queryTime_ = 0L;
            onChanged();
            return this;
        }

        private java.util.List<Integer> parameterIds_ = java.util.Collections.emptyList();

        private void ensureParameterIdsIsMutable() {
            if (!((bitField0_ & 0x00000002) == 0x00000002)) {
                parameterIds_ = new java.util.ArrayList<Integer>(parameterIds_);
                bitField0_ |= 0x00000002;
            }
        }

        /**
         * <code>repeated int32 parameter_ids = 2;</code>
         */
        public java.util.List<Integer>
        getParameterIdsList() {
            return java.util.Collections.unmodifiableList(parameterIds_);
        }

        /**
         * <code>repeated int32 parameter_ids = 2;</code>
         */
        public int getParameterIdsCount() {
            return parameterIds_.size();
        }

        /**
         * <code>repeated int32 parameter_ids = 2;</code>
         */
        public int getParameterIds(int index) {
            return parameterIds_.get(index);
        }

        /**
         * <code>repeated int32 parameter_ids = 2;</code>
         */
        public Builder setParameterIds(
                int index, int value) {
            ensureParameterIdsIsMutable();
            parameterIds_.set(index, value);
            onChanged();
            return this;
        }

        /**
         * <code>repeated int32 parameter_ids = 2;</code>
         */
        public Builder addParameterIds(int value) {
            ensureParameterIdsIsMutable();
            parameterIds_.add(value);
            onChanged();
            return this;
        }

        /**
         * <code>repeated int32 parameter_ids = 2;</code>
         */
        public Builder addAllParameterIds(
                Iterable<? extends Integer> values) {
            ensureParameterIdsIsMutable();
            com.google.protobuf.AbstractMessageLite.Builder.addAll(
                    values, parameterIds_);
            onChanged();
            return this;
        }

        /**
         * <code>repeated int32 parameter_ids = 2;</code>
         */
        public Builder clearParameterIds() {
            parameterIds_ = java.util.Collections.emptyList();
            bitField0_ = (bitField0_ & ~0x00000002);
            onChanged();
            return this;
        }

        public final Builder setUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return this;
        }

        public final Builder mergeUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return this;
        }


        // @@protoc_insertion_point(builder_scope:ConfigQueryRequest)
    }

    // @@protoc_insertion_point(class_scope:ConfigQueryRequest)
    private static final ConfigQueryRequest DEFAULT_INSTANCE;

    static {
        DEFAULT_INSTANCE = new ConfigQueryRequest();
    }

    public static ConfigQueryRequest getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ConfigQueryRequest>
            PARSER = new com.google.protobuf.AbstractParser<ConfigQueryRequest>() {
        public ConfigQueryRequest parsePartialFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return new ConfigQueryRequest(input, extensionRegistry);
        }
    };

    public static com.google.protobuf.Parser<ConfigQueryRequest> parser() {
        return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ConfigQueryRequest> getParserForType() {
        return PARSER;
    }

    public ConfigQueryRequest getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

}

