// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gbt3260.proto

package com.nevt.gbt32960.message;

public interface PlatformMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PlatformMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .ConfigQueryRequest config_query = 2;</code>
   */
  ConfigQueryRequest getConfigQuery();
  /**
   * <code>optional .ConfigQueryRequest config_query = 2;</code>
   */
  ConfigQueryRequestOrBuilder getConfigQueryOrBuilder();

  /**
   * <code>optional .ConfigSetupRequest config_setup = 3;</code>
   */
  ConfigSetupRequest getConfigSetup();
  /**
   * <code>optional .ConfigSetupRequest config_setup = 3;</code>
   */
  ConfigSetupRequestOrBuilder getConfigSetupOrBuilder();

  /**
   * <code>optional .RemoteUpgradeCommand upgrade = 4;</code>
   */
  RemoteUpgradeCommand getUpgrade();
  /**
   * <code>optional .RemoteUpgradeCommand upgrade = 4;</code>
   */
  RemoteUpgradeCommandOrBuilder getUpgradeOrBuilder();

  /**
   * <code>optional .Warning warning = 5;</code>
   */
  Warning getWarning();
  /**
   * <code>optional .Warning warning = 5;</code>
   */
  WarningOrBuilder getWarningOrBuilder();

  /**
   * <code>optional .ControlCommand control = 6;</code>
   */
  ControlCommand getControl();
  /**
   * <code>optional .ControlCommand control = 6;</code>
   */
  ControlCommandOrBuilder getControlOrBuilder();

  /**
   * <code>optional .TerminalClockCorrect clock_correct = 7;</code>
   */
  TerminalClockCorrect getClockCorrect();
  /**
   * <code>optional .TerminalClockCorrect clock_correct = 7;</code>
   */
  TerminalClockCorrectOrBuilder getClockCorrectOrBuilder();

  /**
   * <code>optional .EmptyResponse empty_response = 8;</code>
   */
  EmptyResponse getEmptyResponse();
  /**
   * <code>optional .EmptyResponse empty_response = 8;</code>
   */
  EmptyResponseOrBuilder getEmptyResponseOrBuilder();

  /**
   * <code>optional .ProtoResponse proto_response = 9;</code>
   */
  ProtoResponse getProtoResponse();
  /**
   * <code>optional .ProtoResponse proto_response = 9;</code>
   */
  ProtoResponseOrBuilder getProtoResponseOrBuilder();

  public PlatformMessage.MessageCase getMessageCase();
}
