// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gbt3260.proto

package com.nevt.gbt32960.message;

public interface RealTimeReportOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RealTimeReport)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int64 record_time = 1;</code>
   */
  long getRecordTime();

  /**
   * <code>optional bool reissue = 2;</code>
   */
  boolean getReissue();

  /**
   * <code>optional .VehicleState vehicleState = 3;</code>
   */
  boolean hasVehicleState();
  /**
   * <code>optional .VehicleState vehicleState = 3;</code>
   */
  VehicleState getVehicleState();
  /**
   * <code>optional .VehicleState vehicleState = 3;</code>
   */
  VehicleStateOrBuilder getVehicleStateOrBuilder();

  /**
   * <code>repeated .MotorState motor = 4;</code>
   */
  java.util.List<MotorState>
      getMotorList();
  /**
   * <code>repeated .MotorState motor = 4;</code>
   */
  MotorState getMotor(int index);
  /**
   * <code>repeated .MotorState motor = 4;</code>
   */
  int getMotorCount();
  /**
   * <code>repeated .MotorState motor = 4;</code>
   */
  java.util.List<? extends MotorStateOrBuilder>
      getMotorOrBuilderList();
  /**
   * <code>repeated .MotorState motor = 4;</code>
   */
  MotorStateOrBuilder getMotorOrBuilder(
      int index);

  /**
   * <code>optional .FuelCell fuelCell = 5;</code>
   */
  boolean hasFuelCell();
  /**
   * <code>optional .FuelCell fuelCell = 5;</code>
   */
  FuelCell getFuelCell();
  /**
   * <code>optional .FuelCell fuelCell = 5;</code>
   */
  FuelCellOrBuilder getFuelCellOrBuilder();

  /**
   * <code>optional .Engine engine = 6;</code>
   */
  boolean hasEngine();
  /**
   * <code>optional .Engine engine = 6;</code>
   */
  Engine getEngine();
  /**
   * <code>optional .Engine engine = 6;</code>
   */
  EngineOrBuilder getEngineOrBuilder();

  /**
   * <code>optional .VehicleLocation location = 7;</code>
   */
  boolean hasLocation();
  /**
   * <code>optional .VehicleLocation location = 7;</code>
   */
  VehicleLocation getLocation();
  /**
   * <code>optional .VehicleLocation location = 7;</code>
   */
  VehicleLocationOrBuilder getLocationOrBuilder();

  /**
   * <code>optional .Extremum extremum = 8;</code>
   */
  boolean hasExtremum();
  /**
   * <code>optional .Extremum extremum = 8;</code>
   */
  Extremum getExtremum();
  /**
   * <code>optional .Extremum extremum = 8;</code>
   */
  ExtremumOrBuilder getExtremumOrBuilder();

  /**
   * <code>optional .Alarm alarm = 9;</code>
   */
  boolean hasAlarm();
  /**
   * <code>optional .Alarm alarm = 9;</code>
   */
  Alarm getAlarm();
  /**
   * <code>optional .Alarm alarm = 9;</code>
   */
  AlarmOrBuilder getAlarmOrBuilder();

  /**
   * <code>repeated .ChargeableSubsystemElectric chargeSystemElectric = 10;</code>
   */
  java.util.List<ChargeableSubsystemElectric>
      getChargeSystemElectricList();
  /**
   * <code>repeated .ChargeableSubsystemElectric chargeSystemElectric = 10;</code>
   */
  ChargeableSubsystemElectric getChargeSystemElectric(int index);
  /**
   * <code>repeated .ChargeableSubsystemElectric chargeSystemElectric = 10;</code>
   */
  int getChargeSystemElectricCount();
  /**
   * <code>repeated .ChargeableSubsystemElectric chargeSystemElectric = 10;</code>
   */
  java.util.List<? extends ChargeableSubsystemElectricOrBuilder>
      getChargeSystemElectricOrBuilderList();
  /**
   * <code>repeated .ChargeableSubsystemElectric chargeSystemElectric = 10;</code>
   */
  ChargeableSubsystemElectricOrBuilder getChargeSystemElectricOrBuilder(
      int index);

  /**
   * <code>repeated .ChargeableSubsystemTemperature chargeSystemTemperature = 11;</code>
   */
  java.util.List<ChargeableSubsystemTemperature>
      getChargeSystemTemperatureList();
  /**
   * <code>repeated .ChargeableSubsystemTemperature chargeSystemTemperature = 11;</code>
   */
  ChargeableSubsystemTemperature getChargeSystemTemperature(int index);
  /**
   * <code>repeated .ChargeableSubsystemTemperature chargeSystemTemperature = 11;</code>
   */
  int getChargeSystemTemperatureCount();
  /**
   * <code>repeated .ChargeableSubsystemTemperature chargeSystemTemperature = 11;</code>
   */
  java.util.List<? extends ChargeableSubsystemTemperatureOrBuilder>
      getChargeSystemTemperatureOrBuilderList();
  /**
   * <code>repeated .ChargeableSubsystemTemperature chargeSystemTemperature = 11;</code>
   */
  ChargeableSubsystemTemperatureOrBuilder getChargeSystemTemperatureOrBuilder(
      int index);
}
