// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gbt3260.proto

package com.nevt.gbt32960.message;

public interface RemoteUpgradeCommandOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ime.iov.gbt32960.RemoteUpgradeCommand)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int64 request_time = 11;</code>
   */
  long getRequestTime();

  /**
   * <pre>
   *拨号点名称
   * </pre>
   *
   * <code>optional string dial_name = 1;</code>
   */
  String getDialName();
  /**
   * <pre>
   *拨号点名称
   * </pre>
   *
   * <code>optional string dial_name = 1;</code>
   */
  com.google.protobuf.ByteString
      getDialNameBytes();

  /**
   * <pre>
   *拨号用户名
   * </pre>
   *
   * <code>optional string dial_account = 2;</code>
   */
  String getDialAccount();
  /**
   * <pre>
   *拨号用户名
   * </pre>
   *
   * <code>optional string dial_account = 2;</code>
   */
  com.google.protobuf.ByteString
      getDialAccountBytes();

  /**
   * <pre>
   *拨号密码
   * </pre>
   *
   * <code>optional string dial_password = 3;</code>
   */
  String getDialPassword();
  /**
   * <pre>
   *拨号密码
   * </pre>
   *
   * <code>optional string dial_password = 3;</code>
   */
  com.google.protobuf.ByteString
      getDialPasswordBytes();

  /**
   * <pre>
   *地址
   * </pre>
   *
   * <code>optional string address = 4;</code>
   */
  String getAddress();
  /**
   * <pre>
   *地址
   * </pre>
   *
   * <code>optional string address = 4;</code>
   */
  com.google.protobuf.ByteString
      getAddressBytes();

  /**
   * <pre>
   * </pre>
   *
   * <code>optional int32 port = 5;</code>
   */
  int getPort();

  /**
   * <pre>
   *车载终端制造商ID
   * </pre>
   *
   * <code>optional string terminal_manufacturer_id = 6;</code>
   */
  String getTerminalManufacturerId();
  /**
   * <pre>
   *车载终端制造商ID
   * </pre>
   *
   * <code>optional string terminal_manufacturer_id = 6;</code>
   */
  com.google.protobuf.ByteString
      getTerminalManufacturerIdBytes();

  /**
   * <code>optional string hardware_version = 7;</code>
   */
  String getHardwareVersion();
  /**
   * <code>optional string hardware_version = 7;</code>
   */
  com.google.protobuf.ByteString
      getHardwareVersionBytes();

  /**
   * <pre>
   *固件版本
   * </pre>
   *
   * <code>optional string firmware_version = 8;</code>
   */
  String getFirmwareVersion();
  /**
   * <pre>
   *固件版本
   * </pre>
   *
   * <code>optional string firmware_version = 8;</code>
   */
  com.google.protobuf.ByteString
      getFirmwareVersionBytes();

  /**
   * <code>optional string upgrade_url = 9;</code>
   */
  String getUpgradeUrl();
  /**
   * <code>optional string upgrade_url = 9;</code>
   */
  com.google.protobuf.ByteString
      getUpgradeUrlBytes();

  /**
   * <pre>
   *连接到升级服务器时限
   * </pre>
   *
   * <code>optional int32 upgrade_time_limit = 10;</code>
   */
  int getUpgradeTimeLimit();
}
