// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gbt3260.proto

package com.nevt.gbt32960.message;

public interface TerminalResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TerminalResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string vin = 1;</code>
   */
  String getVin();
  /**
   * <code>optional string vin = 1;</code>
   */
  com.google.protobuf.ByteString
      getVinBytes();

  /**
   * <code>optional .ConfigQueryResponse config_query = 2;</code>
   */
  ConfigQueryResponse getConfigQuery();
  /**
   * <code>optional .ConfigQueryResponse config_query = 2;</code>
   */
  ConfigQueryResponseOrBuilder getConfigQueryOrBuilder();

  /**
   * <code>optional bool setup_success = 3;</code>
   */
  boolean getSetupSuccess();

  /**
   * <code>optional bool control_success = 4;</code>
   */
  boolean getControlSuccess();

  public TerminalResponse.MessageCase getMessageCase();
}
